---

- name: Create the script
  template:
    src: ../templates/create_database_if_not_exists.j2
    dest: "/tmp/create_database_if_not_exists.sh"
    owner: root
    group: root
    mode: '755'

- name: Execute script
  shell:
    cmd: /tmp/create_database_if_not_exists.sh

- name: Remove script
  shell:
    cmd: rm /tmp/create_database_if_not_exists.sh
